project:
  type: website
  output-dir: docs

website:
  title: "Ruiqing Cai&reg; Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual

